version: '3.8'
services:
  app:
    container_name: shindex
    build: .
    ports:
      - "4344:4344"
    environment:
      - SERVER_PORT=4344
      - TZ=Africa/Lagos
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - APP_URL=${APP_URL}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - OPENLIST_SERVER_URL=${OPENLIST_SERVER_URL}
      - OPENLIST_API_KEY=${OPENLIST_API_KEY}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_USER_ID=${JELLYFIN_USER_ID}
    volumes:
      - ./config.json:/app/config.json
      - ./db.json:/app/db.json
      - ./jf_override.json:/app/jf_override.json
      - ./jellyfin_cache.json:/app/jellyfin_cache.json
      - ./watchlists:/app/watchlists
      - ./users_expirations.json:/app/users_expirations.json
      - ./activity_logs.json:/app/activity_logs.json
